input [7:0] minuend;
input [7:0] subtrahend;
output [7:0] difference;

wire inv_subtrahend_7;
wire inv_subtrahend_6;
wire inv_subtrahend_5;
wire inv_subtrahend_4;
wire inv_subtrahend_3;
wire inv_subtrahend_2;
wire inv_subtrahend_1;
wire inv_subtrahend_0;

wire negator_carry_0;
wire negator_carry_1;
wire negator_carry_2;
wire negator_carry_3;
wire negator_carry_4;
wire negator_carry_5;
wire negator_carry_6;
wire negator_carry_7;

wire neg_subtrahend_7;
wire neg_subtrahend_6;
wire neg_subtrahend_5;
wire neg_subtrahend_4;
wire neg_subtrahend_3;
wire neg_subtrahend_2;
wire neg_subtrahend_1;
wire neg_subtrahend_0;

wire carryout0;
wire carryout1;
wire carryout2;
wire carryout3;
wire carryout4;
wire carryout5;
wire carryout6;
wire carryout7;

wire carryin1;
wire carryin2;
wire carryin3;
wire carryin4;
wire carryin5;
wire carryin6;
wire carryin7;

wire sum1;
wire sum2;
wire sum3;
wire sum4;
wire sum5;
wire sum6;
wire sum7;

wire temp1_1;
wire temp1_2;
wire temp1_3;
wire temp1_4;
wire temp1_5;
wire temp1_6;
wire temp1_7;

wire temp2_1;
wire temp2_2;
wire temp2_3;
wire temp2_4;
wire temp2_5;
wire temp2_6;
wire temp2_7;

assign inv_subtrahend_7 = ~ subtrahend[7];
assign inv_subtrahend_6 = ~ subtrahend[6];
assign inv_subtrahend_5 = ~ subtrahend[5];
assign inv_subtrahend_4 = ~ subtrahend[4];
assign inv_subtrahend_3 = ~ subtrahend[3];
assign inv_subtrahend_2 = ~ subtrahend[2];
assign inv_subtrahend_1 = ~ subtrahend[1];
assign inv_subtrahend_0 = ~ subtrahend[0];

assign negator_carry_0 = inv_subtrahend_0;
assign negator_carry_1 = negator_carry_0 & inv_subtrahend_1;
assign negator_carry_2 = negator_carry_1 & inv_subtrahend_2;
assign negator_carry_3 = negator_carry_2 & inv_subtrahend_3;
assign negator_carry_4 = negator_carry_3 & inv_subtrahend_4;
assign negator_carry_5 = negator_carry_4 & inv_subtrahend_5;
assign negator_carry_6 = negator_carry_5 & inv_subtrahend_6;
assign negator_carry_7 = negator_carry_6 & inv_subtrahend_7;

assign neg_subtrahend_0 = ~ inv_subtrahend_0;
assign neg_subtrahend_1 = negator_carry_0 ^ inv_subtrahend_1;
assign neg_subtrahend_2 = negator_carry_1 ^ inv_subtrahend_2;
assign neg_subtrahend_3 = negator_carry_2 ^ inv_subtrahend_3;
assign neg_subtrahend_4 = negator_carry_3 ^ inv_subtrahend_4;
assign neg_subtrahend_5 = negator_carry_4 ^ inv_subtrahend_5;
assign neg_subtrahend_6 = negator_carry_5 ^ inv_subtrahend_6;
assign neg_subtrahend_7 = negator_carry_6 ^ inv_subtrahend_7;

assign difference[0] = minuend[0] ^ neg_subtrahend_0;
assign carryout0 = minuend[0] & neg_subtrahend_0;
assign carryin1 = carryout0;
assign sum1 = minuend[1] ^ neg_subtrahend_1;
assign temp1_1 = carryin1 & sum1;
assign temp2_1 = minuend[1] & neg_subtrahend_1;
assign carryout1 = temp1_1 | temp2_1;
assign difference[1] = carryin1 ^ sum1;
assign carryin2 = carryout1;
assign sum2 = minuend[2] ^ neg_subtrahend_2;
assign temp1_2 = carryin2 & sum2;
assign temp2_2 = minuend[2] & neg_subtrahend_2;
assign carryout2 = temp1_2 | temp2_2;
assign difference[2] = carryin2 ^ sum2;
assign carryin3 = carryout2;
assign sum3 = minuend[3] ^ neg_subtrahend_3;
assign temp1_3 = carryin3 & sum3;
assign temp2_3 = minuend[3] & neg_subtrahend_3;
assign carryout3 = temp1_3 | temp2_3;
assign difference[3] = carryin3 ^ sum3;
assign carryin4 = carryout3;
assign sum4 = minuend[4] ^ neg_subtrahend_4;
assign temp1_4 = carryin4 & sum4;
assign temp2_4 = minuend[4] & neg_subtrahend_4;
assign carryout4 = temp1_4 | temp2_4;
assign difference[4] = carryin4 ^ sum4;
assign carryin5 = carryout4;
assign sum5 = minuend[5] ^ neg_subtrahend_5;
assign temp1_5 = carryin5 & sum5;
assign temp2_5 = minuend[5] & neg_subtrahend_5;
assign carryout5 = temp1_5 | temp2_5;
assign difference[5] = carryin5 ^ sum5;
assign carryin6 = carryout5;
assign sum6 = minuend[6] ^ neg_subtrahend_6;
assign temp1_6 = carryin6 & sum6;
assign temp2_6 = minuend[6] & neg_subtrahend_6;
assign carryout6 = temp1_6 | temp2_6;
assign difference[6] = carryin6 ^ sum6;
assign carryin7 = carryout6;
assign sum7 = minuend[7] ^ neg_subtrahend_7;
assign temp1_7 = carryin7 & sum7;
assign temp2_7 = minuend[7] & neg_subtrahend_7;
assign carryout7 = temp1_7 | temp2_7;
assign difference[7] = carryin7 ^ sum7;

